# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nick Payne
email: nick@nickpayne.com
description: > # this means to ignore newlines until "baseurl:"
  Sydney alt-bluegrass troubadour Nick Payne might have remained a weekend picker with a drawer full of songs, but the 
  stars aligned when a move back to Sydney after working around Australia coincided with an impulse purchase of his 
  dream guitar (a Martin D28). A friend turned him on to Ryan Adams _Heartbreaker_ album, and Nick Payne discovered to 
  his surprise that he was a country music fan. With a new musical direction and a wellspring of creativity, drawing 
  inspiration from the traditional and modern Americana canon, as well as Australian alt-country and roots, he returned 
  to performing, playing and writing with renewed focus.
baseurl: # the subpath of your site, e.g. /blog
url: 'http://www.nickpayne.com' # the base hostname & protocol for your site, e.g. http://example.com

# Socials
facebook: https://www.facebook.com/nickpayneandthe/
instagram: https://www.instagram.com/nickpayneandthe/
spotify: https://open.spotify.com/artist/4jpkKVoBhZAHLfFRKwTnn6
songkick: https://www.songkick.com/artists/1679689-nick-payne
youtube: https://www.youtube.com/channel/UC-pjeH6nlEMCclCXOJk1QVQ

# Pagination settings
paginate: 5
paginate_path: "/blog/page-:num/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - bower_components
  - bower.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - README.md
  - yarn.lock
